title: "CADLabs Ethereum Research Model Documentation"
# logo: media/_.png
only_build_toc_files: true
execute:
  execute_notebooks: "off"
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
